# zshrc
# ----------

export ZSH=$HOME/.oh-my-zsh
export GOPATH="$HOME/.go"
export RBENV_ROOT='/usr/local/var/rbenv'
export PATH="/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/bin:$GOPATH/bin"

ZSH_THEME="tlk"
DISABLE_AUTO_TITLE="true"
plugins=(vagrant go git rails ruby python web-search brew bower encode64 gem gradle jsontools last-working-dir node npm osx perl pep8 pip sudo)

source $ZSH/oh-my-zsh.sh
source ~/.aliases
source ~/.env

if which rbenv > /dev/null; then
    eval "$(rbenv init -)";
fi

unsetopt autocd

[[ -s $(brew --prefix)/etc/autojump.sh ]] && . $(brew --prefix)/etc/autojump.sh
