module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "scope-empty": [2, "never"],
    "scope-enum": [
      2,
      "always",
      [
        "kde",
        "cli",
        "code",
        "config",
        "setup",
        "sync",
        "shell",
        "prompt",
        "vim",
        "emacs",
        "editor",
        "tmux",
        "herdr",
        "terminal",
        "git",
        "github",
        "ssh",
        "theme",
        "fonts",
        "packages",
        "langs",
        "backup",
        "ai",
        "readme",
        "docs",
        "deps",
        "build",
        "ci",
        "release",
        "tooling",
        "tests",
        "security",
        "linux",
        "macos",
      ],
    ],
  },
};
