#!/usr/bin/env bash

read -p "copy dotfiles from home directory to repository? (y/n) " -r

if [[ "$REPLY" =~ ^[Yy]$ ]]; then
  cd src/ || exit 1

  while IFS= read -r -d '' file; do
    if [[ $(diff "$file" "$HOME/$file") ]]; then
      echo -e "updating $file..."

      cp "$HOME/$file" "$file"
    fi
  done < <(find . -type f -print0)

  echo -e "\nupdated repository with latest files from $HOME directory."
else
  echo -e "\naborting..."
fi

exit 0
